### ISSUE TITLE
Change FT references

### ISSUE THREAD

**Issue by aarmour** [PearsonEducation/he-origami#5]
**TODO** once a name has been chosen:
- [ ] Change FT references in the text
- [ ] Replace FT image assets
- [ ] Update spec link in README.md
- [ ] Update the `public users please instead raise an issue on the repo` footer link
- [ ] "Fix" British spelling :wink:

**TODO** once the registry is operational:
- [ ] Update registry link in the header

**Comment by marcdonovan** [comment]
Images are broken. Sample http://pearsoneducation.github.io/he-origami/docs/developer-guide/build-service/

**Comment by aarmour** [comment]
Yep—I anticipate we will configure a DNS record (origami.pearsoned.com or something similar) to point to the gh-pages site, after which the relative URLs will be valid. Added a todo item for configuring DNS.

**Comment by aarmour** [comment]
Name has been finalized: HE Origami

**Comment by triblondon** [comment]
> "Fix" British spelling

I find food is the biggest area of disagreement. American recipes are impossible to follow without a dictionary, but fortunately I don't think we used any courgettes, coriander, aubergines, biscuits or chips in origami so you probably just need to remove a few Us here and there.

Fun fact: there are several regions within the U.S. where UK English is the official language.
